#!/usr/bin/env bash
# weekly_tick.sh — the deterministic weekly run. NOT LLM-driven: this script is
# pure bookkeeping. The only LLM-authored content is the prose produced *inside*
# `review new` / `forum round` (stubbed for now).
#
# Pipeline:  world advance -> review new -> forum round -> export -> check
#            -> world close -> astro build -> git branch/commit/push -> gh PR
#
# `check` aborts the run on failure. main is NEVER committed to directly; the PR
# is the human review gate. Re-running after a half-failure is safe (the steps
# are idempotent and the week-already-open guard prevents a double advance).
#
# Usage:  scripts/weekly_tick.sh [--no-git] [--dry-run]
set -euo pipefail

# --- locate repo root (this script lives in <root>/scripts) ------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

NO_GIT=0
DRY=""
for arg in "$@"; do
  case "$arg" in
    --no-git) NO_GIT=1 ;;
    --dry-run) DRY="--dry-run" ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# --- pick the Python interpreter (prefer the project venv) -------------------
if [[ -x "$ROOT/backend/.venv/bin/python" ]]; then
  PY="$ROOT/backend/.venv/bin/python"
else
  PY="$(command -v python3)"
fi
# The CLI resolves DB/migration paths relative to backend/, so run it from there.
engine() { ( cd "$ROOT/backend" && "$PY" -m engine "$@" ); }

echo "==> Ensuring schema is migrated"
engine init

echo "==> world advance"
engine $DRY world advance

echo "==> review new"
engine $DRY review new

echo "==> forum round"
engine $DRY forum round

echo "==> export canon -> Astro content"
engine $DRY export

echo "==> check (aborts on failure)"
engine check

if [[ -n "$DRY" ]]; then
  echo "==> dry-run complete; no DB writes, no git. Stopping before close/build."
  exit 0
fi

echo "==> world close (finalize the week)"
engine world close

WEEK="$(engine world cursor)"          # e.g. 2026-W22
BRANCH="week-${WEEK}"
echo "==> Astro build for ${WEEK}"
( cd site && npm run build )

if [[ "$NO_GIT" -eq 1 ]]; then
  echo "==> --no-git set; skipping branch/commit/PR. Built ${WEEK}."
  exit 0
fi

# --- git: branch off main, commit SOURCE only, push, open PR -----------------
if [[ -n "$(git status --porcelain)" || ! "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH" ]]; then
  git checkout main
  git pull --ff-only origin main || true
  git checkout -B "$BRANCH"
  git add -A                      # .gitignore keeps DB/dist/venv out
  git commit -m "Column: week ${WEEK}

Automated weekly tick: advance -> review -> forum -> export -> check.
Generated by scripts/weekly_tick.sh. Review prose is the only LLM-authored part."
  git push -u origin "$BRANCH"

  if command -v gh >/dev/null 2>&1; then
    gh pr create --base main --head "$BRANCH" \
      --title "Column: week ${WEEK}" \
      --body "Automated weekly tick for ${WEEK}. \`check\` passed locally and runs again on this PR. Merging deploys to Pages."
  else
    echo "NOTE: gh not installed — push done, open the PR manually." >&2
  fi
else
  echo "Nothing to commit for ${WEEK}."
fi
